# Generated by Django 4.0.6 on 2022-07-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
